<a class="page-back" href="/">&larr;</a>
<h1 class="page-header">
    Login admin
</h1>
<?php if ($this->get('error_login') == true): ?>
    <h2>Login failed, try again'</h2>
<?php endif; ?>
<form action="?page=admin_login" method="POST">
    <div>
        <label for="name">Name</label>
        <input type="text" id="name" name="admin[name]" />
    </div>
    <div>
        <label for="password">Password</label>
        <input type="text" id="password" name="admin[password]" />
    </div>

    <input type="submit" value="Login">
</form>