<a class="page-back" href="/">&larr;</a>
<h1 class="page-header">Products My Cart</h1>
<?php if (empty($this->get('items')->getItems())): ?>
    <h1>Cart empty</h1>
<?php endif; ?>
<ul class="product-list">
    <?php foreach ($this->get('items') as $_item):
        $_product = $_item->getProduct();
        ?>
        <li class="product-item">
            <img class="product-item_image" src="<?php echo $_product->getImage(); ?>" />
            <a href="/?page=product_view&id=<?php echo $_product->getId(); ?>">
                <h2 class="product-item_title"><?php echo $_product->getName(); ?></h2>
            </a>
            <span class="product-item_sku"><?php echo $_product->getSku(); ?></span>
            <div>
                <span
                    class="product-item_price <?php if ($_product->isSpecialPriceApplied()): ?>old-price<?php endif; ?>">
                    $<?php echo $_product->getPrice(); ?>
                </span>
                <?php if ($_product->isSpecialPriceApplied()): ?>
                    <span class="product-item_price">$<?php echo $_product->getSpecialPrice(); ?></span>
                <?php endif; ?>
            </div>
            <p><?php echo $_item->getQty() ?> qty</p>
            <form action="/?page=cart_update" method="post">
                <p><input type="hidden" id="product_id" name="product_id" value="<?php echo $_item->getProductId() ?>"></p>
                <p><input type="hidden" id="qty" name="qty" value="1"></p>
                <p><input type="submit" value="+"></p>
            </form>
            <form action="/?page=cart_update" method="post">
                <p><input type="hidden" id="product_id" name="product_id" value="<?php echo $_item->getProductId() ?>"></p>
                <p><input type="hidden" id="qty" name="qty" value="-1"></p>
                <p><input type="submit" value="-"></p>
            </form>
            <form action="/?page=cart_remove" method="post">
                <p><input type="hidden" id="product_id" name="product_id" value="<?php echo $_item->getProductId() ?>"></p>
                <p><input type="submit" value="Remove from cart"></p>
            </form>
        </li>
    <?php endforeach; ?>
</ul>