
<a class="page-back" href="/">&larr;</a>
<h1 class="page-header">
    Add new User
</h1>
<div class="view-customer">
    <form method="post" action="/?page=customerAdmin_add">
        <div>
            <label>Name</label>
            <input type="text" name="add[name]" value=""/>
        </div>

        <div>
            <label>Email</label>
            <input type="text" name="add[email]" value=""/>
        </div>

        <div>
            <label>New password</label>
            <input type="text" name="add[password]" value=""/>
        </div>

        <div>
            <input type="submit"/>
        </div>
    </form>
</div>