<a class="page-back" href="/">&larr;</a>
<h1 class="page-header">
    Login To The Site
</h1>

<form action="?page=customer_login" method="POST">
    <div>
        <label for="name">Name</label>
        <input type="text" id="name" name="customer[name]" />
    </div>
    <div>
        <label for="password">Password</label>
        <input type="text" id="password" name="customer[password]" />
    </div>

    <input type="submit" value="Login">
</form>