<h1 class="page-header">Our Product List</h1>
<a href="/?page=customerAdmin_add">Добавить нового пользователя</a>
<ul class="product-list">
    <?php for ($page = 1; $page <= $this->get('pages')->pageCount; $page++): ?>
        <a href="/?page=customerAdmin_list&p=<?php echo $page; ?>"><?php echo $page; ?></a>
    <?php endfor; ?>
    <table border="1">
    <thead>
    <tr>
        <th>
            <form action="/?page=customerAdmin_list" method="post">
                <input type="hidden" name="filter_by" value="name" />
                <input type="text" name="filter_value" value="<?php if ($this->get('customers')->getLikeBy()['name'] == 'name') echo $this->get('customers')->getLikeBy()['value']?>"/>
                <input type="submit" value="Фильтр"/>
            </form>
        </th>
        <th>
            <form action="/?page=customerAdmin_list" method="post">
                <input type="hidden" name="filter_by" value="email" />
                <input type="text" name="filter_value" value="<?php if ($this->get('customers')->getLikeBy()['name'] == 'email') echo $this->get('customers')->getLikeBy()['value']?>"/>
                <input type="submit" value="Фильтр"/>
            </form>
        </th>
        <th>

        </th>
    </tr>
    <tr>
        <th>
            <form action="/?page=customerAdmin_list" method="post">
                <input type="hidden" name="order_by" value="name" />
                <input type="submit" value="Имя"/>
            </form>
        </th>
        <th>
            <form action="/?page=customerAdmin_list" method="post">
                <input type="hidden" name="order_by" value="email" />
                <input type="submit" value="E-mail"/>
            </form>
        </th>
        <th>Действие</th>
    </tr>
    </thead>
        <tbody>

        <?php foreach ($this->get('customers') as $_customer): ?>
        <tr>
            <td><a href="/?page=customerAdmin_edit&customer_id=<?php echo $_customer->getId(); ?>"><?php echo $_customer->getName(); ?></a></td>
            <td><a href="/?page=customerAdmin_edit&customer_id=<?php echo $_customer->getId(); ?>"><?php echo $_customer->getEmail(); ?></a></td>
            <td><a href="/?page=customerAdmin_remove&customer_id=<?php echo $_customer->getId(); ?>">Удалить</a></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</ul>
