        <article>
            <ul class="">
                <?php foreach ($products as $_product): ?>
                    <li class="clearfix">
                        <div class="block-img">
                            <img src="<?php echo $_product->getImage(); ?>" />
                        </div>
                        <!--                <span>--><?php //echo $_product->getSku(); ?><!--</span>-->
                        <div class="right-block">
                            <h2>Наименование товара: <?php echo $_product->getName(); ?></h2>
                            <span class="price">Цена: <?php echo $_product->getPrice(); ?></span>
                            <span class="spec-price">Сециальная цена: <?php echo $_product->getSpecialPrice(); ?></span>
                            <a href="index.php/?page=product_view&id=<?php echo $_product->getId(); ?>" class="bay">Купить</a>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </article>
