<a class="page-back" href="/">&larr;</a>
<h1 class="page-header">
    <?php echo $product->getName(); ?>
</h1>

<img class="product-view_image" src="<?php echo $product->getImage(); ?>" />
<div class="product-view_sku"><?php echo $product->getSku(); ?></div>
<div>
    <span
        class="product-item_price <?php if ($product->isSpecialPriceApplied()): ?>old-price<?php endif; ?>">
        $<?php echo $product->getPrice(); ?>
    </span>
    <?php if($product->isSpecialPriceApplied()): ?>
        <span class="product-item_price">$<?php echo $product->getSpecialPrice(); ?></span>
    <?php endif; ?>
</div>
<form action="/?page=cart_add" method="post">
    <p><input type="hidden" id="product_id" name="product_id" value="<?php echo $product->getId(); ?>"></p>
    <p><input type="hidden" id="qty" name="qty" value="1"></p>
    <p><input type="submit" value="Add to cart"></p>
</form>
<div class="clear-fix"></div>
<div>
    <h3>Comment list:</h3>
    <ul class="product-list">
        <?php foreach ($reviews as $_review): ?>
            <li class="product-item">
                <p>Name User: <?php echo $_review->getName(); ?></p>
                <p>Comment content: <?php echo $_review->getText(); ?></p>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php for ($page = 1; $page <= $pagesComment->pageCount; $page++): ?>
        <a href="/?page=product_view&id<?php echo $product->getId(); ?>&c=<?php echo $page; ?>"><?php echo $page; ?></a>
    <?php endfor; ?>

</div>