<a class="page-back" href="/">&larr;</a>
<h1 class="page-header">
    <?php echo $product->getName(); ?>
</h1>

<img class="product-view_image" src="<?php echo $product->getImage(); ?>" />
<div class="product-view_sku"><?php echo $product->getSku(); ?></div>
<div>
    <span
        class="product-item_price <?php if ($product->isSpecialPriceApplied()): ?>old-price<?php endif; ?>">
        $<?php echo $product->getPrice(); ?>
    </span>
    <?php if($product->isSpecialPriceApplied()): ?>
        <span class="product-item_price">$<?php echo $product->getSpecialPrice(); ?></span>
    <?php endif; ?>
</div>
<form action="/?page=cart_add" method="post">
    <p><input type="hidden" id="product_id" name="product_id" value="<?php echo $product->getId(); ?>"></p>
    <p><input type="hidden" id="qty" name="qty" value="1"></p>
    <p><input type="submit" value="Add to cart"></p>
</form>
<div class="clear-fix"></div>
<div>
    <h3>Comment list:</h3>
    <ul class="product-list">
        <?php foreach ($reviews as $_review): ?>
            <li class="product-item">
                <p>Name User: <?php echo $_review->getName(); ?></p>
                <p>Comment content: <?php echo $_review->getText(); ?></p>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php for ($page = 1; $page <= $pagesComment->pageCount; $page++): ?>
        <a href="/?page=product_view&id<?php echo $product->getId(); ?>&c=<?php echo $page; ?>"><?php echo $page; ?></a>
    <?php endfor; ?>
    <form class="new-review" action="/?page=productReview_add" method="post">
        <input type="hidden" name="token" value="<?php echo $this->session()->getToken(); ?>" />
        <input type="hidden" name="product_id" value="<?php echo $product->getId(); ?>"/>
        <div>
            <label>Name</label>
            <input type="text" name="name"/>
        </div>

        <div>
            <label>Email</label>
            <input type="text" name="email"/>
        </div>

        <div>
            <label>Rating</label>
            <select name="rating">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
            </select>
        </div>

        <div>
            <label>Text</label>
            <textarea name="text"></textarea>
        </div>

        <div>
            <input type="submit"/>
        </div>
    </form>
</div>